from sqlalchemy.orm import Session
from app.models.skill import Skill
from app.schemas.skill import SkillCreate


def get_skill_by_scraped_id(db: Session, scraped_id: str) -> Skill | None:
    return db.query(Skill).filter(Skill.scraped_id == scraped_id).first()


def get_all_skills(db: Session) -> list[Skill]:
    return db.query(Skill).all()


def create_or_update_skill(db: Session, skill_data: SkillCreate) -> Skill:
    existing = get_skill_by_scraped_id(db, skill_data.scraped_id)

    if existing:
        existing.name = skill_data.name
        db.commit()
        db.refresh(existing)
        return existing

    db_skill = Skill(
        scraped_id=skill_data.scraped_id,
        name=skill_data.name,
    )  # id is auto-generated by the model default
    db.add(db_skill)
    db.commit()
    db.refresh(db_skill)
    return db_skill