
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import localFont from "next/font/local";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ClientLayout from "./ClientLayout";


const iranyekan = localFont({
  src: [
    { path: "../data/fonts/IRANYekanXFaNum-Light.woff2", weight: "300" },
    { path: "../data/fonts/IRANYekanXFaNum-Regular.woff2", weight: "400" },
    { path: "../data/fonts/IRANYekanXFaNum-Bold.woff2", weight: "700" },
    { path: "../data/fonts/IRANYekanXFaNum-Black.woff2", weight: "900" },
    { path: "../data/fonts/IRANYekanXFaNum-ExtraBlack.woff2", weight: "950" },
  ],
  variable: "--font-fa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {

  return (
      <html
        lang="en"
        dir='rtl'
        className={cn("h-full", "antialiased", iranyekan.className)}
      >
        <ClientLayout>{children}</ClientLayout>
      </html>
  );
}
