"""add completed_projects_count to freelancers

Revision ID: 1008aa6295d2
Revises: 2da5bd6e4bd3
Create Date: 2026-06-26 09:50:16.199923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1008aa6295d2'
down_revision: Union[str, None] = '2da5bd6e4bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancers', sa.Column('completed_projects_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancers', 'completed_projects_count')
    # ### end Alembic commands ###
