"""add projects_scraped checkpoint to freelancers

Revision ID: 2da5bd6e4bd3
Revises: 367338ff6620
Create Date: 2026-06-25 16:12:48.855861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da5bd6e4bd3'
down_revision: Union[str, None] = '367338ff6620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancers', sa.Column('projects_scraped', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_freelancers_projects_scraped'), 'freelancers', ['projects_scraped'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freelancers_projects_scraped'), table_name='freelancers')
    op.drop_column('freelancers', 'projects_scraped')
    # ### end Alembic commands ###
