"""add freelancers table, restore skill scraped_id

Revision ID: 367338ff6620
Revises: 0818e3ad9c39
Create Date: 2026-06-25 11:40:19.179419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367338ff6620'
down_revision: Union[str, None] = '0818e3ad9c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scraped_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_scraped_id'), 'skills', ['scraped_id'], unique=True)
    op.create_table('freelancers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scraped_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraped_id', 'category_id', name='uq_freelancer_category')
    )
    op.create_index(op.f('ix_freelancers_category_id'), 'freelancers', ['category_id'], unique=False)
    op.create_index(op.f('ix_freelancers_id'), 'freelancers', ['id'], unique=False)
    op.create_index(op.f('ix_freelancers_scraped_id'), 'freelancers', ['scraped_id'], unique=False)
    op.add_column('projects', sa.Column('final_budget', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'projects_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects_skills', type_='foreignkey')
    op.drop_column('projects', 'final_budget')
    op.drop_index(op.f('ix_freelancers_scraped_id'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_id'), table_name='freelancers')
    op.drop_index(op.f('ix_freelancers_category_id'), table_name='freelancers')
    op.drop_table('freelancers')
    op.drop_index(op.f('ix_skills_scraped_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
