"""added usd table 2

Revision ID: 4e75ec3f00f3
Revises: bf0b6ab18681
Create Date: 2026-07-06 15:00:33.937484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e75ec3f00f3'
down_revision: Union[str, None] = 'bf0b6ab18681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usd',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usd')
    # ### end Alembic commands ###
