"""add skills and projects_skills tables

Revision ID: c991a4af6c56
Revises: ba0db0e4eb82
Create Date: 2026-06-24 21:57:39.857789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c991a4af6c56'
down_revision: Union[str, None] = 'ba0db0e4eb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scraped_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_scraped_id'), 'skills', ['scraped_id'], unique=True)
    op.create_table('projects_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_project_skill')
    )
    op.create_index(op.f('ix_projects_skills_id'), 'projects_skills', ['id'], unique=False)
    op.create_index(op.f('ix_projects_skills_project_id'), 'projects_skills', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_skills_skill_id'), 'projects_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_skills_skill_id'), table_name='projects_skills')
    op.drop_index(op.f('ix_projects_skills_project_id'), table_name='projects_skills')
    op.drop_index(op.f('ix_projects_skills_id'), table_name='projects_skills')
    op.drop_table('projects_skills')
    op.drop_index(op.f('ix_skills_scraped_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
